### ISSUE TITLE
Update for CYS instructions?

### ISSUE THREAD

**Issue by smileygamer13** [SpiredMoth/s3spp#1]
Will there ever be an update for the instructions? it makes 0 sense to me and I'd like to use it... but just throwing a list of items in my face and variations of HOW to CYS doesn't tell me how to actually navigate it. It just gives me lists without any way of knowing HOW to best CYS

**Comment by SpiredMoth** [comment]
I have added some explanation of the CYS Calculator to the spreadsheet now.  Feel free to leave a comment on the spreadsheet itself if you have further questions, comments, or concerns that are *not* about the work-in-progress Python app in this repository.
